version: "3.9"
services:
  # app:
  #   build: .
  #   ports: 
  #     - "4000:4000"
    
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      # POSTGRES_USER: alex.shakun
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
